# Copyright (c) 2024 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build utils Dockerfile

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-utils-dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/utils__*.Dockerfile"
  pull_request:
    paths:
      - ".github/workflows/build-utils-dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/utils__*.Dockerfile"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-utils-dockerfile:
    name: Build utils Dockerfile
    uses: paulsengroup/nchg-nf/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/utils__*.Dockerfile"

    permissions:
      contents: read
      packages: write
